backend = "glx";
vsync = true;
use-damage = true;


blur-method = "gaussian";
blur-size = 4;
blur-deviation = 1.8;
blur-background = true;
blur-background-frame = false;
blur-background-fixed = false;

blur-background-exclude = [
    "window_type = 'dock'",
    "window_type = 'desktop'",
    "_GTK_FRAME_EXTENTS@"
];

corner-radius = 0;
shadow = false;

active-opacity = 1.0;
inactive-opacity = 1.0;
frame-opacity = 1.0;

wintypes:
{
  tooltip = { fade = true; shadow = false; opacity = 1.0; focus = true; };
  dnd = { shadow = false; };
  popup_menu = { opacity = 1.0; };
  dropdown_menu = { opacity = 1.0; };
};
